combinations:
  - combination: 1
    robot:
      policy: "orca"

  - combination: 2
    robot:
      policy: "social_force"
 
  - combination: 3
    robot:
      policy: "selfAttn_merge_srnn"

  # - combination: 5
  #   robot:
  #     policy: "srnn"