combinations:
  - combination: 1
    robot:
      policy: "orca"

  # - combination: 2
  #   robot:
  #     policy: "social_force"

  # - combination: 3
  #   robot:
  #     policy: "srnn"
  
  - combination: 4
    robot:
      policy: "selfAttn_merge_srnn"
